package de.velospot.data.local.database

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import de.velospot.data.local.dao.BikeParkingSpaceDao
import de.velospot.data.local.entity.BikeParkingSpaceEntity
import de.velospot.data.local.entity.FavoriteParkingSpaceEntity
import java.io.File

/**
 * Room database for storing bike parking space information locally.
 * Provides single-threaded access through a singleton pattern.
 *
 * The [FavoriteParkingSpaceEntity] table is still declared here so the on-device
 * schema (and the bundled asset) stay byte-for-byte unchanged, but favourites are
 * no longer read or written through this database: they now live in the isolated
 * [FavoritesDatabase], which a parking-data destructive migration can never wipe.
 * The legacy table is left untouched (a one-time copy in [FavoritesDatabase]
 * migrates any pre-existing favourites out of it).
 */
@Database(
    entities = [BikeParkingSpaceEntity::class, FavoriteParkingSpaceEntity::class],
    version = 4,
    exportSchema = true
)
abstract class BikeParkingDatabase : RoomDatabase() {

    /**
     * Returns the DAO for bike parking space database operations.
     */
    abstract fun bikeParkingSpaceDao(): BikeParkingSpaceDao


    companion object {
        @Volatile
        private var instance: BikeParkingDatabase? = null

        /** Primary seed asset (also carries the Room schema + room_master_table). */
        private const val SEED_ASSET = "bike_parking_germany.db"

        /**
         * Additional country datasets bundled in `assets/`, each generated by the
         * same `scripts/extract_osm_parking.py` (identical schema). Their rows are
         * merged into the single [SEED_ASSET]-seeded table on first open / upgrade
         * so the bounding-box queries transparently return spots in these countries
         * too. OSM element IDs are globally unique, so no cross-country collisions
         * are expected; `INSERT OR IGNORE` guards against any rare duplicate.
         */
        private val EXTRA_COUNTRY_ASSETS = listOf(
            "bike_parking_france.db",
            "bike_parking_luxembourg.db"
        )

        private val SPACE_COLUMNS =
            "id,name,latitude,longitude,address,capacity,isCovered,imageUrl,operator,type,sourceLayer,lastUpdated"

        /**
         * Name of the composite B-tree index backing the viewport bounding-box
         * query in [de.velospot.data.local.dao.BikeParkingSpaceDao.getSpacesInBoundingBox].
         * It must match the index declared on
         * [de.velospot.data.local.entity.BikeParkingSpaceEntity]; if the two ever
         * diverge Room's schema validation would trigger a destructive rebuild.
         */
        internal const val LAT_LON_INDEX_NAME = "idx_parking_lat_lon"

        /**
         * Idempotent DDL that (re)creates the viewport index.
         *
         * Investigation of performance finding #7: this app runs on the *platform*
         * SQLite (no bundled requery/SQLCipher, no custom open-helper factory), so a
         * real spatial index (`CREATE VIRTUAL TABLE … USING rtree`) is not a safe
         * option — the R*Tree module is not guaranteed to be compiled into every
         * device's SQLite and would abort DB open (and destructively wipe the seeded
         * parking data) on devices without it. A composite `(latitude, longitude)`
         * B-tree is therefore the correct tool here: for typical map viewports the
         * latitude band is highly selective, so SQLite range-scans latitude via this
         * index and filters longitude in-index before touching the row.
         *
         * The index physically lives in the bundled asset DBs. This `IF NOT EXISTS`
         * statement is a self-healing guarantee: it runs at the end of the country
         * merge so the newly inserted France/Luxembourg rows are indexed, and it
         * repairs the index should a future asset rebuild ever ship without it —
         * preventing a silent, catastrophic destructive rebuild of user data.
         */
        private const val CREATE_LAT_LON_INDEX =
            "CREATE INDEX IF NOT EXISTS `$LAT_LON_INDEX_NAME` " +
                "ON `bike_parking_spaces` (`latitude`, `longitude`)"

        /**
         * Get singleton instance of the database.
         * Thread-safe initialization using double-checked locking.
         *
         * @param context Application context
         * @return Singleton instance of BikeParkingDatabase
         */
        fun getInstance(context: Context): BikeParkingDatabase {
            return instance ?: synchronized(this) {
                instance ?: createDatabase(context).also { instance = it }
            }
        }

        /**
         * Create the Room database instance with proper configuration.
         *
         * @param context Application context
         * @return New BikeParkingDatabase instance
         */
        private fun createDatabase(context: Context): BikeParkingDatabase {
            val appContext = context.applicationContext
            return Room.databaseBuilder(
                appContext,
                BikeParkingDatabase::class.java,
                // New name intentionally differs from the legacy "velospot_database.db" used
                // by the Trier-WFS era (up to v1.0.5).  Using a fresh name guarantees that
                // every device — whether a clean install or an upgrade — gets a new database
                // file which Room will seed from the OSM asset on first open.
                // The old file is simply ignored; old favorites (which referenced Trier WFS IDs
                // that no longer exist) are not migrated.
                "velospot_osm.db"
            )
                .createFromAsset(SEED_ASSET)
                // v3 → v4 is a data-only migration: it merges the additional bundled
                // country datasets (France, Luxembourg, …) into the Germany-seeded
                // table. It runs both on fresh installs (the v3 asset is copied, then
                // migrated up to v4) and on app upgrades from an existing v3 database —
                // the latter preserving the user's favorites and any Germany data.
                .addMigrations(extraCountriesMigration(appContext))
                .fallbackToDestructiveMigration(dropAllTables = true)
                .build()
        }

        /**
         * Builds the data-only migration that imports every dataset in
         * [EXTRA_COUNTRY_ASSETS] into the main `bike_parking_spaces` table.
         */
        private fun extraCountriesMigration(context: Context): Migration =
            object : Migration(3, 4) {
                override fun migrate(db: SupportSQLiteDatabase) {
                    EXTRA_COUNTRY_ASSETS.forEach { asset -> importCountryAsset(context, db, asset) }
                    // Guarantee the viewport index covers the freshly merged rows and
                    // self-heal it if a future asset ever ships without it. Idempotent,
                    // schema-neutral (the index is already part of the v4 schema, so no
                    // version bump / identity-hash change is required) and safe inside
                    // Room's migration transaction (CREATE INDEX, unlike ATTACH, is
                    // permitted within a transaction).
                    db.execSQL(CREATE_LAT_LON_INDEX)
                }
            }

        /**
         * Test-only accessor exposing the exact production v3 → v4 migration so an
         * instrumented migration test can validate it against the checked-in schema
         * baseline and assert the viewport index is present after the country merge.
         * Not for production use.
         */
        @androidx.annotation.VisibleForTesting
        internal fun migration3To4ForTest(context: Context): Migration =
            extraCountriesMigration(context)

        /**
         * Copies one bundled country DB out of `assets/` into a temp file, opens it
         * read-only and bulk-inserts its parking rows into [target].
         *
         * Note: this deliberately reads the source via a separate [SQLiteDatabase]
         * connection rather than `ATTACH DATABASE`, because Room runs migrations
         * inside a transaction and SQLite forbids `ATTACH` within a transaction.
         */
        private fun importCountryAsset(
            context: Context,
            target: SupportSQLiteDatabase,
            assetName: String
        ) {
            val tmp = File(context.cacheDir, "import_$assetName")
            context.assets.open(assetName).use { input ->
                tmp.outputStream().use { output -> input.copyTo(output) }
            }
            try {
                SQLiteDatabase.openDatabase(
                    tmp.path, null, SQLiteDatabase.OPEN_READONLY
                ).use { source ->
                    val insert = target.compileStatement(
                        "INSERT OR IGNORE INTO bike_parking_spaces ($SPACE_COLUMNS) " +
                            "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)"
                    )
                    source.rawQuery("SELECT $SPACE_COLUMNS FROM bike_parking_spaces", null).use { c ->
                        while (c.moveToNext()) {
                            insert.clearBindings()
                            insert.bindString(1, c.getString(0))                    // id (NOT NULL)
                            bindNullableText(insert, 2, c, 1)                       // name
                            insert.bindDouble(3, c.getDouble(2))                    // latitude
                            insert.bindDouble(4, c.getDouble(3))                    // longitude
                            bindNullableText(insert, 5, c, 4)                       // address
                            bindNullableLong(insert, 6, c, 5)                       // capacity
                            bindNullableLong(insert, 7, c, 6)                       // isCovered (0/1)
                            bindNullableText(insert, 8, c, 7)                       // imageUrl
                            bindNullableText(insert, 9, c, 8)                       // operator
                            insert.bindString(10, c.getString(9))                   // type (NOT NULL)
                            insert.bindString(11, c.getString(10))                  // sourceLayer (NOT NULL)
                            insert.bindLong(12, c.getLong(11))                      // lastUpdated (NOT NULL)
                            insert.executeInsert()
                        }
                    }
                }
            } finally {
                tmp.delete()
            }
        }

        private fun bindNullableText(
            stmt: androidx.sqlite.db.SupportSQLiteStatement,
            index: Int,
            cursor: android.database.Cursor,
            column: Int
        ) {
            if (cursor.isNull(column)) stmt.bindNull(index) else stmt.bindString(index, cursor.getString(column))
        }

        private fun bindNullableLong(
            stmt: androidx.sqlite.db.SupportSQLiteStatement,
            index: Int,
            cursor: android.database.Cursor,
            column: Int
        ) {
            if (cursor.isNull(column)) stmt.bindNull(index) else stmt.bindLong(index, cursor.getLong(column))
        }
    }
}
