package de.velospot.data.local.database

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import de.velospot.data.local.dao.BikeParkingSpaceDao
import de.velospot.data.local.entity.BikeParkingSpaceEntity
import de.velospot.data.local.entity.FavoriteParkingSpaceEntity
import java.io.File

/**
 * Room database for storing bike parking space information locally.
 * Provides single-threaded access through a singleton pattern.
 *
 * The [FavoriteParkingSpaceEntity] table is still declared here so the on-device
 * schema (and the bundled asset) stay byte-for-byte unchanged, but favourites are
 * no longer read or written through this database: they now live in the isolated
 * [FavoritesDatabase], which a parking-data destructive migration can never wipe.
 * The legacy table is left untouched (a one-time copy in [FavoritesDatabase]
 * migrates any pre-existing favourites out of it).
 */
@Database(
    entities = [BikeParkingSpaceEntity::class, FavoriteParkingSpaceEntity::class],
    version = 4,
    exportSchema = true
)
abstract class BikeParkingDatabase : RoomDatabase() {

    /**
     * Returns the DAO for bike parking space database operations.
     */
    abstract fun bikeParkingSpaceDao(): BikeParkingSpaceDao


    companion object {
        @Volatile
        private var instance: BikeParkingDatabase? = null

        /** Default on-device database file name. */
        internal const val DATABASE_NAME = "velospot_osm.db"

        /** Primary seed asset (also carries the Room schema + room_master_table). */
        private const val SEED_ASSET = "bike_parking_germany.db"


        /** Alias used while a country asset is `ATTACH`ed for the bulk import. */
        private const val ATTACH_ALIAS = "country_src"

        /**
         * Additional country datasets bundled in `assets/`, each generated by the
         * same `scripts/extract_osm_parking.py` (identical schema). Their rows are
         * merged into the single [SEED_ASSET]-seeded table on first open / upgrade
         * so the bounding-box queries transparently return spots in these countries
         * too. OSM element IDs are globally unique, so no cross-country collisions
         * are expected; `INSERT OR IGNORE` guards against any rare duplicate.
         */
        private val EXTRA_COUNTRY_ASSETS = listOf(
            "bike_parking_france.db",
            "bike_parking_luxembourg.db"
        )

        /**
         * Get singleton instance of the database.
         * Thread-safe initialization using double-checked locking.
         *
         * @param context Application context
         * @return Singleton instance of BikeParkingDatabase
         */
        fun getInstance(context: Context): BikeParkingDatabase {
            return instance ?: synchronized(this) {
                instance ?: buildDatabase(context.applicationContext, DATABASE_NAME)
                    .also { instance = it }
            }
        }

        /**
         * Builds a database instance with the production configuration. Exposed
         * (internal) with a customisable file name so instrumented tests can create
         * throw-away databases that exercise the real seeding + country merge.
         *
         * @param context Application context
         * @param name    On-device database file name
         * @return New BikeParkingDatabase instance
         */
        internal fun buildDatabase(context: Context, name: String): BikeParkingDatabase {
            val appContext = context.applicationContext
            return Room.databaseBuilder(
                appContext,
                BikeParkingDatabase::class.java,
                // New name intentionally differs from the legacy "velospot_database.db" used
                // by the Trier-WFS era (up to v1.0.5).  Using a fresh name guarantees that
                // every device — whether a clean install or an upgrade — gets a new database
                // file which Room will seed from the OSM asset on first open.
                // The old file is simply ignored; old favorites (which referenced Trier WFS IDs
                // that no longer exist) are not migrated.
                name
            )
                .createFromAsset(SEED_ASSET)
                // v3 → v4 is a data-only version bump (the managed schema is identical).
                // The country-data merge is NOT done in the migration: Room runs migrations
                // inside a transaction, and SQLite forbids `ATTACH DATABASE` inside a
                // transaction — which is why the merge previously fell back to a slow
                // row-by-row loop. The merge now happens once in
                // [mergeExtraCountriesIfNeeded] from the non-transactional `onOpen`
                // callback, where a single fast `ATTACH … INSERT OR IGNORE … SELECT` per
                // country replaces thousands of Kotlin↔SQLite round-trips.
                .addMigrations(dataOnlyV3ToV4Migration())
                .addCallback(mergeCallback(appContext))
                .fallbackToDestructiveMigration(dropAllTables = true)
                .build()
        }

        /**
         * v3 → v4 migration. The managed schema is unchanged between the two versions
         * (this is a data-only bump), so the only work here is a defensive, idempotent
         * recreation of the viewport index — which is already shipped in every bundled
         * asset, but this guarantees the post-migration `TableInfo` validation passes
         * even for any older on-device database that predates it.
         */
        private fun dataOnlyV3ToV4Migration(): Migration =
            object : Migration(3, 4) {
                override fun migrate(db: SupportSQLiteDatabase) {
                    db.execSQL(CountryMergeSql.ENSURE_INDEX_SQL)
                }
            }

        /**
         * Room callback performing the one-time merge of the bundled extra-country
         * datasets. [RoomDatabase.Callback.onOpen] runs on Room's normal open path (so
         * the invalidation tracker is already initialised — no
         * `room_table_modification_log` crash) but, crucially, **outside** any
         * transaction, which is what allows `ATTACH DATABASE` here.
         */
        private fun mergeCallback(context: Context): RoomDatabase.Callback =
            object : RoomDatabase.Callback() {
                override fun onOpen(db: SupportSQLiteDatabase) {
                    super.onOpen(db)
                    mergeExtraCountriesIfNeeded(context, db)
                }
            }

        /**
         * Imports every dataset in [EXTRA_COUNTRY_ASSETS] into the main
         * `bike_parking_spaces` table exactly once per database instance.
         *
         * Exactly-once & crash-safety are anchored on a **DB-resident** marker —
         * SQLite's `PRAGMA application_id`. Room does not use `application_id` (it
         * tracks its schema via `user_version`), so writing a sentinel there is
         * invisible to Room's schema/identity-hash validation and does not count as
         * a schema change:
         *  - `onOpen` reads `application_id`; if it already equals the sentinel the
         *    merge is fully done and is skipped entirely.
         *  - Otherwise every asset is imported with a single `INSERT OR IGNORE …
         *    SELECT`, which SQLite runs as one atomic (auto-commit) transaction. A
         *    process death mid-insert rolls that statement back, so the DB is never
         *    left half-merged.
         *  - Only **after all** assets have been imported is the sentinel written.
         *    If the process dies before that write, `application_id` is still at its
         *    baseline, so the next open re-runs the whole merge; `INSERT OR IGNORE`
         *    (primary key = globally-unique OSM id) makes every re-run a no-op for
         *    already-present rows, so no duplicates are ever created.
         *
         * Crucially, because the marker lives *inside* the database file, a
         * destructive fallback that deletes the DB and re-copies the Germany-only
         * v3 asset resets `application_id` back to its baseline — so the merge
         * correctly re-runs and restores the country union, instead of being
         * permanently skipped (which is exactly the regression a persisted
         * SharedPreferences flag would have caused).
         */
        internal fun mergeExtraCountriesIfNeeded(context: Context, db: SupportSQLiteDatabase) {
            if (readApplicationId(db) == CountryMergeSql.APPLICATION_ID_SENTINEL) return
            // Attempt every asset (don't short-circuit), so an interrupted run still
            // makes forward progress; a failed one just defers the sentinel to a later open.
            val allImported = EXTRA_COUNTRY_ASSETS
                .map { asset -> runCatching { importCountryAsset(context, db, asset) }.isSuccess }
                .all { it }
            // Stamp the DB-resident "fully merged" sentinel only once *every* country
            // has been imported. A partial/interrupted run leaves application_id at its
            // baseline, so the next open resumes; INSERT OR IGNORE keeps it duplicate-free.
            if (allImported) db.execSQL(CountryMergeSql.setApplicationIdSql())
        }

        /** Reads the DB-resident merge marker (`PRAGMA application_id`). */
        private fun readApplicationId(db: SupportSQLiteDatabase): Int =
            db.query(CountryMergeSql.READ_APPLICATION_ID_SQL).use { cursor ->
                if (cursor.moveToFirst()) cursor.getInt(0) else CountryMergeSql.APPLICATION_ID_BASELINE
            }

        /**
         * Copies one bundled country DB out of `assets/` into a temp file, `ATTACH`es
         * it and bulk-inserts its parking rows into the main table with a single
         * `INSERT OR IGNORE … SELECT`. The temp file and the attachment are always
         * released, even on failure.
         */
        private fun importCountryAsset(
            context: Context,
            db: SupportSQLiteDatabase,
            assetName: String
        ) {
            val tmp = File(context.cacheDir, "import_$assetName")
            context.assets.open(assetName).use { input ->
                tmp.outputStream().use { output -> input.copyTo(output) }
            }
            try {
                db.execSQL(CountryMergeSql.attachSql(ATTACH_ALIAS), arrayOf<Any>(tmp.path))
                try {
                    db.execSQL(CountryMergeSql.insertSelectSql(ATTACH_ALIAS))
                } finally {
                    db.execSQL(CountryMergeSql.detachSql(ATTACH_ALIAS))
                }
            } finally {
                tmp.delete()
            }
        }
    }
}
